config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views import defaults as default_views
from django.views.generic import TemplateView

urlpatterns = [
    # path("", TemplateView.as_view(template_name="pages/home.html"), name="home"),
    path("about/", TemplateView.as_view(template_name="pages/about.html"), name="about"),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path("accounts/", include("allauth.urls")),
    # Your stuff: custom urls includes go here
    path("", include("djgram.users.urls", namespace="users")),
    path("posts/", include("djgram.posts.urls", namespace="posts")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

djgram/posts/urls.py
from django.urls import path
from . import views

app_name='posts'

urlpatterns=[
    path('', views.index, name='index'),
    path('create/', views.post_create, name='post_create'),
    path('<int:post_id>/post_update/', views.post_update, name='post_update'),
    path('<int:post_id>/post_like/', views.post_like, name='post_like'),
    path('<int:post_id>/comment_create/', views.comment_create, name='comment_create'),
    path('<int:cmt_id>/comment_delete/', views.comment_delete, name='comment_delete'),
]

djgram/users/urls.py
from django.urls import path
# from djgram.users.views import (
#     user_detail_view,
#     user_redirect_view,
#     user_update_view,
# )
from . import views

app_name = "users"
urlpatterns = [
    path('', views.main, name='main'),
    path('signup/', views.signup, name='signup'),
]

djgram/posts/models.py
from django.db import models
from djgram.users import models as user_model


class TimeStamp(models.Model):
    create_date=models.DateTimeField(auto_now_add=True)
    update_date=models.DateTimeField(auto_now_add=True)

    class Meta:
        abstract = True

class Post(TimeStamp):
    author=models.ForeignKey(user_model.User, on_delete=models.CASCADE, related_name='post_author')
    image=models.ImageField(blank=False)
    caption=models.TextField(blank=False)
    image_likes=models.ManyToManyField(user_model.User, related_name='post_image_likes', blank=True)

    def __str__(self) :
        return f"{self.author} : {self.caption}"

class Comment(TimeStamp):
    author=models.ForeignKey(user_model.User, on_delete=models.CASCADE, related_name='comment_author')
    post=models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comment_post')
    contents=models.TextField(blank=True, max_length=100)

djgram/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.urls import reverse
from django.utils.translation import gettext_lazy as _


class User(AbstractUser):

    Gender=[
        ('M', 'Male'),
        ('F', 'Female'),
        ('C', 'Custom')
    ]

    name = models.CharField(_("Name of User"), blank=True, max_length=255)
    user_name = models.CharField(max_length=255,blank=True )
    profile_photo = models.ImageField(blank=True)
    desc=models.TextField(max_length=400, blank=True)
    gender=models.CharField(choices=Gender, max_length=100, blank=True)

    followers=models.ManyToManyField("self")
    following=models.ManyToManyField("self")

    def get_absolute_url(self) -> str:

        return reverse("users:detail", kwargs={"username": self.username})

djgram/posts/forms.py
from django import forms
from .models import Post, Comment

class CreatePostForm(forms.ModelForm):
    class Meta :
        model=Post
        fields=['caption', 'image']
        labels = {'caption': '설명', 'image':'이미지'}

class UpdatePostForm(forms.ModelForm):
    class Meta:
        model=Post
        fields=['caption']
        
class CommentForm(forms.ModelForm):
    contents=forms.CharField(widget=forms.Textarea(attrs={'rows':4, 'cols':78,}), label='')
    class Meta:
        model=Comment
        fields=['contents']

djgram/users/forms.py
from allauth.account.forms import SignupForm
from allauth.socialaccount.forms import SignupForm as SocialSignupForm
from django.contrib.auth import forms as admin_forms
from django.contrib.auth import get_user_model
from django.utils.translation import gettext_lazy as _
from django import forms as django_forms

User = get_user_model()


class UserAdminChangeForm(admin_forms.UserChangeForm):
    class Meta(admin_forms.UserChangeForm.Meta):
        model = User


class UserAdminCreationForm(admin_forms.UserCreationForm):
    """
    Form for User Creation in the Admin Area.
    To change user signup, see UserSignupForm and UserSocialSignupForm.
    """

    class Meta(admin_forms.UserCreationForm.Meta):
        model = User
        error_messages = {
            "username": {"unique": _("This username has already been taken.")},
        }


class UserSignupForm(SignupForm):
    """
    Form that will be rendered on a user sign up section/screen.
    Default fields will be added automatically.
    Check UserSocialSignupForm for accounts created from social.
    """


class UserSocialSignupForm(SocialSignupForm):
    """
    Renders the form when user has signed up using social accounts.
    Default fields will be added automatically.
    See UserSignupForm otherwise.
    """

class SignUpForm(django_forms.ModelForm):
    class Meta:
        model=User
        fields=['email', 'name', 'username', 'password']
        # labels={'email' : '이메일', 
        #         'name': '이름', 
        #         'username': '닉네임', 
        #         'password' : '비밀번호'}
        widgets={'email':django_forms.TextInput(attrs={'placeholder':'이메일주소'}),
                 'name':django_forms.TextInput(attrs={'placeholder':'이름'}),
                 'username':django_forms.TextInput(attrs={'placeholder':'닉네임'}),
                 'password':django_forms.PasswordInput(attrs={'placeholder':'비밀번호'}),
                }

    def save(self, commit=True):
        user=super().save(commit=False)
        user.set_password(self.cleaned_data['password'])
        if commit:
            user.save()
        return user

djgram/posts/views.py
from django.shortcuts import render, get_object_or_404, HttpResponseRedirect, redirect
from djgram.users.models import User as user_model
from django.db.models import Q
from django.urls import reverse
from django.http import JsonResponse

from . import models, serializers
from .forms import *

# Create your views here.
def index(request):
    if request.method == 'GET':
        if request.user.is_authenticated :
            user=get_object_or_404(user_model, pk=request.user.id)
            following = user.following.all()
            posts=models.Post.objects.filter(Q(author__in = following) | Q(author=user)).order_by('-create_date')
            comment_form=CommentForm()
            serializer=serializers.PostSerializer(posts, many=True)
            return render(request, 'posts/main.html', 
                          {'posts' : serializer.data, 
                           'comment_form': comment_form})

def post_create(request):
    if request.method == 'GET':
        form=CreatePostForm()
        return render(request, 'posts/create.html', {'form':form})
    
    elif request.method == 'POST':
        if request.user.is_authenticated:
            user=get_object_or_404(user_model, pk=request.user.id)
            form=CreatePostForm(request.POST, request.FILES)   # 장고form에 post에서 가져온 데이터를 바로 넣을 수
            
            if form.is_valid():
                post=form.save(commit=False)
                post.author=user
                post.save()
            else : print(form.errors)

            # image=request.FILES['image']
            # caption=request.POST['caption']

            # new_post=models.Post.objects.create(
            #     author=user,
            #     image=image,
            #     caption=caption
            # )
            # new_post.save()
            return HttpResponseRedirect(reverse('posts:index'))

        else : return render(request, 'users/main.html') ## 로그인 확인 안되면, 로그인 페이지로


def post_update(request, post_id):
    if request.user.is_authenticated:

        post=get_object_or_404(models.Post, pk=post_id)
        if request.user != post.author :
            redirect(reverse('posts:index'))

        if request.method == 'GET':
            form=UpdatePostForm(instance=post)
            return render(request, 'posts/post_update.html', {'form':form, 'post':post})
        
        elif request.method == 'POST':
            form=UpdatePostForm(request.POST)
            if form.is_valid():
                post.caption=form.cleaned_data['caption']
                post.save()
            return redirect(reverse('posts:index'))

    else : redirect(reverse('users:main'))

def post_like(request, post_id):
    response_body={'result':''}
    if request.user.is_authenticated:
        if request.method == 'POST':
            post=get_object_or_404(models.Post, pk=post_id)
            existed_user=post.image_likes.filter(pk=request.user.id).exists()

            if existed_user :
                post.image_likes.remove(request.user)
                response_body['result']='dislike'
            
            else :
                post.image_likes.add(pk=request.user)
                response_body['result']='like'

            post.save()
            return JsonResponse(status=200, data=response_body)
    else : return JsonResponse(status=403, data=response_body)

    
def comment_create(request, post_id):
    if request.user.is_authenticated:
        post=get_object_or_404(models.Post, pk=post_id)
        form=CommentForm(request.POST)
        if form.is_valid():
            comment=form.save(commit=False)
            comment.author=request.user
            comment.post=post
            comment.save()
            return HttpResponseRedirect(reverse('posts:index') + '#comment-' + str(comment.id))
        

        else : return render(request, 'users/main.html')


def comment_delete(request, cmt_id):
    if request.user.is_authenticated:
        comment=get_object_or_404(models.Comment, pk=cmt_id)
        if request.user == comment.author :
            comment.delete()
        return redirect(reverse('posts:index'))
    else :
        return render(request, 'users/main.html')

djgram/users/views.py
from django.shortcuts import render
from django.contrib.auth import authenticate, login
from django.http import HttpResponseRedirect
from django.urls import reverse
from .forms import SignUpForm

def main(request):
    if request.method=='GET':
        return render(request, 'users/main.html')
    elif request.method =='POST':
        username=request.POST['username']
        pwd=request.POST['pwd']
        user=authenticate(request, username=username, password=pwd)
    
        if user is not None :
            login(request, user)
            return HttpResponseRedirect(reverse('posts:index'))
        
        else :
            return render(request, 'users/main.html')
        
def signup(request):
    if request.method == 'GET':
        form=SignUpForm()
        return render(request, 'users/signup.html', {'form':form})
    
    elif request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():  ## form이 유효하지 않는 경우는 어떤 경우??
            form.save()

            # 회원가입 후 자동로그인
            # 1) db에서 데이터 가져오기
            username=form.cleaned_data['username']
            password=form.cleaned_data['password']
            user=authenticate(request, username=username, password=password)

            # 2) 로그인 로직
            if user is not None:
                login(request, user)
                return HttpResponseRedirect(reverse('posts:index'))
        
        return render(request, 'users/main.html')
        return render(request, 'users/signup.html', {'form':form})

djgram/templates/posts/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://kit.fontawesome.com/b6455e9a05.js" crossorigin="anonymous"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" type='text/css' href="{% static 'css/posts/main.css'%}">

    <title>Document</title>
</head>
<body>
    <div class="header">
        {% include "posts/header.html" %}
    </div>

    {% block content %}
    {% endblock %}
    <script type="text/javascript" src="{% static 'js/posts.js'%}"></script>

</body>
</html>

djgram/templates/posts/create.html
{% extends 'posts/base.html' %}

{% block content %}
<div class="create">
    <form action="{% url 'posts:post_create' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{form.as_p}}
        <input type="submit" value="Create">
    </form>
</div>
{% endblock content %}

djgram/templates/posts/header.html
{% load static %}
<nav class="navbar navbar-expand-lg bg-light">
    <div class="container-fluid">
      <a class="navbar-brand" href="#">Djgram</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'posts:post_create' %}">create</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Link</a>
          </li>
        
        </ul>
        <form class="d-flex" role="search">
          <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success" type="submit">Search</button>
        </form>
      </div>
    </div>
  </nav>

djgram/templates/posts/index.html
포스

<a href="{%url 'posts:post_create' %}"> 포스트생성 </a>

djgram/templates/posts/main.html
{% extends 'posts/base.html' %}
{% load static %}


{% block content %}

    {% for post in posts %}
    <div class="post_box">
        <div class="header">
            <div class="user_profile">
                {% if post.author.profile_photo != None%}
                    {{post.author.profile_photo}}
                {% else %}
                    <img src="{% static 'images/posts/non_profile.png'%}" alt="no_profile">
                {%endif%}
            <div class="username">{{post.author.username}}</div>
            </div>  

            {%if user.id == post.author.id %}
            <div class="icon">
                <a href="{%url 'posts:post_update' post.id %}">
                    <i class="fa-solid fa-pencil"></i>
                </a>

                <i class="fa-solid fa-trash"></i>

            </div>
            {%endif%}
        </div>

        <div class="post_img">
            <img src= "{{post.image}}">
        </div>

        <button id="like-button-{{post.id}}" onclick="likeClick(this.id)">
            {%if user.id in post.image_likes %}
                <i class="fa-solid fa-heart"></i>
            {%else%}
                <i class="fa-regular fa-heart"></i>
            {%endif%}
        </button>


        <div class="desc_box">
            <div class="image_desc">
                {{post.author.username}}
                {{post.caption}}
            </div>
            <br><br>

            <div class="comments">
                {%for cmt in post.comment_post%}
                    {{cmt.author.username}} : {{cmt.contents}} 
                    {%if user.id == cmt.author.id%}
                        <a href="{%url 'posts:comment_delete' cmt.id %}">
                            <i class="fa-solid fa-trash"></i>
                        </a>
                    {% endif %}
                    <br>
                {%endfor%}
            </div>
        </div>
        <div class="comment_input">
            <form action="{%url 'posts:comment_create' post.id %}" method="post">
                {%csrf_token%}
                {{comment_form}}
                <input type="submit" value="Post">
            </form>
        </div>
    </div>
    <br><br>
    {% endfor %}

{% endblock content %}

djgram/templates/posts/post_update.html
{% extends 'posts/base.html' %}

{% block content %}
<div class="create">
    <form action="{% url 'posts:post_update' post.id%}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{form.as_p}}
        <input type="submit" value="Update">
    </form>
</div>
{% endblock content %}